export const INITIAL_TOOLS = [
  {
    id: 'vscode',
    title: 'VS Code',
    url: 'vscode://',
    category: 'development',
    tags: ['editor', 'code', 'microsoft'],
    usageCount: 1542,
    lastUsed: '2023-11-29T10:30:00',
    status: 'healthy',
    description: 'Code editing. Redefined.',
    icon: 'Code'
  },
  {
    id: 'github',
    title: 'GitHub',
    url: 'https://github.com',
    category: 'development',
    tags: ['git', 'repo', 'collaboration'],
    usageCount: 892,
    lastUsed: '2023-11-29T09:15:00',
    status: 'healthy',
    description: 'Where the world builds software.',
    icon: 'Github'
  },
  {
    id: 'vercel',
    title: 'Vercel',
    url: 'https://vercel.com',
    category: 'deployment',
    tags: ['cloud', 'nextjs', 'serverless'],
    usageCount: 430,
    lastUsed: '2023-11-28T16:45:00',
    status: 'healthy',
    description: 'Develop. Preview. Ship.',
    icon: 'Triangle'
  },
  {
    id: 'figma',
    title: 'Figma',
    url: 'https://figma.com',
    category: 'design',
    tags: ['ui', 'ux', 'prototyping'],
    usageCount: 320,
    lastUsed: '2023-11-27T14:20:00',
    status: 'update_available',
    description: 'The collaborative interface design tool.',
    icon: 'PenTool'
  },
  {
    id: 'chatgpt',
    title: 'ChatGPT',
    url: 'https://chat.openai.com',
    category: 'ai',
    tags: ['llm', 'assistant', 'productivity'],
    usageCount: 1250,
    lastUsed: '2023-11-29T11:00:00',
    status: 'healthy',
    description: 'AI assistant by OpenAI.',
    icon: 'Bot'
  },
  {
    id: 'linear',
    title: 'Linear',
    url: 'https://linear.app',
    category: 'productivity',
    tags: ['issue-tracking', 'agile', 'management'],
    usageCount: 210,
    lastUsed: '2023-11-29T09:00:00',
    status: 'healthy',
    description: 'The issue tracking tool you\'ll enjoy using.',
    icon: 'ListTodo'
  },
  {
    id: 'notion',
    title: 'Notion',
    url: 'https://notion.so',
    category: 'productivity',
    tags: ['notes', 'wiki', 'docs'],
    usageCount: 670,
    lastUsed: '2023-11-28T18:30:00',
    status: 'healthy',
    description: 'All-in-one workspace.',
    icon: 'FileText'
  },
  {
    id: 'docker',
    title: 'Docker',
    url: 'https://www.docker.com/',
    category: 'devops',
    tags: ['container', 'virtualization'],
    usageCount: 150,
    lastUsed: '2023-11-25T11:00:00',
    status: 'warning',
    description: 'OS-level virtualization to deliver software in packages.',
    icon: 'Container'
  },
  {
    id: 'deepseek',
    title: 'DeepSeek',
    url: 'https://chat.deepseek.com',
    category: 'ai',
    tags: ['llm', 'chinese', 'reasoning'],
    usageCount: 890,
    lastUsed: '2023-11-29T10:45:00',
    status: 'healthy',
    description: 'Advanced AI model with strong reasoning capabilities.',
    icon: 'Bot'
  },
  {
    id: 'gemini',
    title: 'Gemini',
    url: 'https://gemini.google.com',
    category: 'ai',
    tags: ['llm', 'google', 'multimodal'],
    usageCount: 1120,
    lastUsed: '2023-11-29T11:30:00',
    status: 'healthy',
    description: 'Google\'s most capable AI model.',
    icon: 'Bot'
  },
  {
    id: 'claude',
    title: 'Claude',
    url: 'https://claude.ai',
    category: 'ai',
    tags: ['llm', 'anthropic', 'assistant'],
    usageCount: 1050,
    lastUsed: '2023-11-29T10:00:00',
    status: 'healthy',
    description: 'Anthropic\'s AI assistant for thoughtful conversations.',
    icon: 'Bot'
  },
  {
    id: 'cursor',
    title: 'Cursor',
    url: 'https://cursor.sh',
    category: 'ai',
    tags: ['code', 'editor', 'ai-powered'],
    usageCount: 780,
    lastUsed: '2023-11-29T09:30:00',
    status: 'healthy',
    description: 'AI-first code editor built for productivity.',
    icon: 'Code'
  },
  {
    id: 'copilot',
    title: 'GitHub Copilot',
    url: 'https://github.com/features/copilot',
    category: 'ai',
    tags: ['code', 'assistant', 'github'],
    usageCount: 950,
    lastUsed: '2023-11-29T08:15:00',
    status: 'healthy',
    description: 'Your AI pair programmer.',
    icon: 'Github'
  },
  {
    id: 'perplexity',
    title: 'Perplexity',
    url: 'https://www.perplexity.ai',
    category: 'ai',
    tags: ['search', 'research', 'llm'],
    usageCount: 620,
    lastUsed: '2023-11-28T20:00:00',
    status: 'healthy',
    description: 'AI-powered answer engine for research.',
    icon: 'Bot'
  },
  {
    id: 'midjourney',
    title: 'Midjourney',
    url: 'https://www.midjourney.com',
    category: 'ai',
    tags: ['image', 'generation', 'art'],
    usageCount: 540,
    lastUsed: '2023-11-27T19:00:00',
    status: 'healthy',
    description: 'AI art generation platform.',
    icon: 'PenTool'
  },
  // Additional Development Tools
  {
    id: 'nextjs',
    title: 'Next.js',
    url: 'https://nextjs.org',
    category: 'development',
    tags: ['react', 'framework', 'ssr'],
    usageCount: 1340,
    lastUsed: '2023-11-29T11:45:00',
    status: 'healthy',
    description: 'The React Framework for Production.',
    icon: 'Code'
  },
  {
    id: 'tailwind',
    title: 'Tailwind CSS',
    url: 'https://tailwindcss.com',
    category: 'development',
    tags: ['css', 'utility', 'styling'],
    usageCount: 1180,
    lastUsed: '2023-11-29T10:20:00',
    status: 'healthy',
    description: 'Rapidly build modern websites without leaving your HTML.',
    icon: 'Code2'
  },
  {
    id: 'typescript',
    title: 'TypeScript',
    url: 'https://www.typescriptlang.org',
    category: 'development',
    tags: ['language', 'types', 'javascript'],
    usageCount: 1420,
    lastUsed: '2023-11-29T09:50:00',
    status: 'healthy',
    description: 'JavaScript with syntax for types.',
    icon: 'Code'
  },
  {
    id: 'stackoverflow',
    title: 'Stack Overflow',
    url: 'https://stackoverflow.com',
    category: 'development',
    tags: ['qa', 'community', 'help'],
    usageCount: 760,
    lastUsed: '2023-11-28T15:30:00',
    status: 'healthy',
    description: 'Where developers learn, share, & build careers.',
    icon: 'Code2'
  },
  // Additional Design Tools
  {
    id: 'canva',
    title: 'Canva',
    url: 'https://www.canva.com',
    category: 'design',
    tags: ['graphics', 'templates', 'social'],
    usageCount: 480,
    lastUsed: '2023-11-28T13:00:00',
    status: 'healthy',
    description: 'Design anything. Publish anywhere.',
    icon: 'PenTool'
  },
  {
    id: 'framer',
    title: 'Framer',
    url: 'https://www.framer.com',
    category: 'design',
    tags: ['prototyping', 'animation', 'web'],
    usageCount: 390,
    lastUsed: '2023-11-27T16:00:00',
    status: 'healthy',
    description: 'Design and publish modern sites.',
    icon: 'PenTool'
  },
  {
    id: 'dribbble',
    title: 'Dribbble',
    url: 'https://dribbble.com',
    category: 'design',
    tags: ['inspiration', 'portfolio', 'community'],
    usageCount: 290,
    lastUsed: '2023-11-26T12:00:00',
    status: 'healthy',
    description: 'Discover the world\'s top designers & creatives.',
    icon: 'PenTool'
  },
  {
    id: 'behance',
    title: 'Behance',
    url: 'https://www.behance.net',
    category: 'design',
    tags: ['portfolio', 'showcase', 'adobe'],
    usageCount: 250,
    lastUsed: '2023-11-25T10:00:00',
    status: 'healthy',
    description: 'Showcase and discover creative work.',
    icon: 'PenTool'
  },
  // Additional Productivity Tools
  {
    id: 'slack',
    title: 'Slack',
    url: 'https://slack.com',
    category: 'productivity',
    tags: ['chat', 'team', 'communication'],
    usageCount: 890,
    lastUsed: '2023-11-29T11:00:00',
    status: 'healthy',
    description: 'Where work happens.',
    icon: 'ListTodo'
  },
  {
    id: 'trello',
    title: 'Trello',
    url: 'https://trello.com',
    category: 'productivity',
    tags: ['kanban', 'project', 'boards'],
    usageCount: 560,
    lastUsed: '2023-11-28T14:00:00',
    status: 'healthy',
    description: 'Trello brings all your tasks, teammates, and tools together.',
    icon: 'CheckSquare'
  },
  {
    id: 'asana',
    title: 'Asana',
    url: 'https://asana.com',
    category: 'productivity',
    tags: ['project', 'management', 'tasks'],
    usageCount: 420,
    lastUsed: '2023-11-27T13:00:00',
    status: 'healthy',
    description: 'Manage your team\'s work, projects, & tasks online.',
    icon: 'ListTodo'
  },
  {
    id: 'obsidian',
    title: 'Obsidian',
    url: 'https://obsidian.md',
    category: 'productivity',
    tags: ['notes', 'knowledge', 'markdown'],
    usageCount: 720,
    lastUsed: '2023-11-29T08:00:00',
    status: 'healthy',
    description: 'A powerful knowledge base on top of a local folder of plain text files.',
    icon: 'FileText'
  },
  // Additional Deployment Tools
  {
    id: 'netlify',
    title: 'Netlify',
    url: 'https://www.netlify.com',
    category: 'deployment',
    tags: ['hosting', 'jamstack', 'cdn'],
    usageCount: 380,
    lastUsed: '2023-11-28T17:00:00',
    status: 'healthy',
    description: 'Build, deploy, and scale modern web projects.',
    icon: 'Rocket'
  },
  {
    id: 'railway',
    title: 'Railway',
    url: 'https://railway.app',
    category: 'deployment',
    tags: ['hosting', 'backend', 'database'],
    usageCount: 290,
    lastUsed: '2023-11-27T15:00:00',
    status: 'healthy',
    description: 'Bring your code, we\'ll handle the rest.',
    icon: 'Rocket'
  },
  {
    id: 'cloudflare',
    title: 'Cloudflare',
    url: 'https://www.cloudflare.com',
    category: 'deployment',
    tags: ['cdn', 'security', 'dns'],
    usageCount: 510,
    lastUsed: '2023-11-28T19:00:00',
    status: 'healthy',
    description: 'The Web Performance & Security Company.',
    icon: 'Rocket'
  },
  // Additional DevOps Tools
  {
    id: 'kubernetes',
    title: 'Kubernetes',
    url: 'https://kubernetes.io',
    category: 'devops',
    tags: ['orchestration', 'containers', 'k8s'],
    usageCount: 340,
    lastUsed: '2023-11-26T14:00:00',
    status: 'healthy',
    description: 'Production-Grade Container Orchestration.',
    icon: 'Server'
  },
  {
    id: 'jenkins',
    title: 'Jenkins',
    url: 'https://www.jenkins.io',
    category: 'devops',
    tags: ['ci', 'automation', 'pipeline'],
    usageCount: 280,
    lastUsed: '2023-11-25T16:00:00',
    status: 'healthy',
    description: 'Build great things at any scale.',
    icon: 'Server'
  },
  {
    id: 'terraform',
    title: 'Terraform',
    url: 'https://www.terraform.io',
    category: 'devops',
    tags: ['iac', 'infrastructure', 'cloud'],
    usageCount: 310,
    lastUsed: '2023-11-27T11:00:00',
    status: 'healthy',
    description: 'Infrastructure as Code to provision and manage any cloud.',
    icon: 'Server'
  },
  {
    id: 'grafana',
    title: 'Grafana',
    url: 'https://grafana.com',
    category: 'devops',
    tags: ['monitoring', 'metrics', 'visualization'],
    usageCount: 260,
    lastUsed: '2023-11-26T10:00:00',
    status: 'healthy',
    description: 'The open observability platform.',
    icon: 'Server'
  },
  // IoT Tools
  {
    id: 'emqx',
    title: 'EMQX',
    url: 'https://www.emqx.io',
    category: 'iot',
    tags: ['mqtt', 'broker', 'messaging'],
    usageCount: 520,
    lastUsed: '2023-11-29T10:30:00',
    status: 'healthy',
    description: 'The most scalable open-source MQTT broker for IoT.',
    icon: 'Server'
  },
  {
    id: 'thingsboard',
    title: 'ThingsBoard',
    url: 'https://thingsboard.io',
    category: 'iot',
    tags: ['platform', 'dashboard', 'devices'],
    usageCount: 380,
    lastUsed: '2023-11-28T16:00:00',
    status: 'healthy',
    description: 'Open-source IoT platform for data collection and visualization.',
    icon: 'Server'
  },
  {
    id: 'nodered',
    title: 'Node-RED',
    url: 'https://nodered.org',
    category: 'iot',
    tags: ['flow', 'automation', 'visual'],
    usageCount: 450,
    lastUsed: '2023-11-29T09:00:00',
    status: 'healthy',
    description: 'Low-code programming for event-driven applications.',
    icon: 'Code'
  },
  {
    id: 'arduino',
    title: 'Arduino',
    url: 'https://www.arduino.cc',
    category: 'iot',
    tags: ['hardware', 'microcontroller', 'embedded'],
    usageCount: 610,
    lastUsed: '2023-11-28T14:30:00',
    status: 'healthy',
    description: 'Open-source electronics platform.',
    icon: 'Container'
  },
  {
    id: 'raspberrypi',
    title: 'Raspberry Pi',
    url: 'https://www.raspberrypi.org',
    category: 'iot',
    tags: ['sbc', 'linux', 'hardware'],
    usageCount: 540,
    lastUsed: '2023-11-27T12:00:00',
    status: 'healthy',
    description: 'Low cost, high performance computers.',
    icon: 'Container'
  },
  {
    id: 'homeassistant',
    title: 'Home Assistant',
    url: 'https://www.home-assistant.io',
    category: 'iot',
    tags: ['smart-home', 'automation', 'open-source'],
    usageCount: 420,
    lastUsed: '2023-11-26T18:00:00',
    status: 'healthy',
    description: 'Open source home automation that puts local control first.',
    icon: 'Server'
  },
  {
    id: 'influxdb',
    title: 'InfluxDB',
    url: 'https://www.influxdata.com',
    category: 'iot',
    tags: ['timeseries', 'database', 'metrics'],
    usageCount: 340,
    lastUsed: '2023-11-25T15:00:00',
    status: 'healthy',
    description: 'Time series database built for IoT and real-time analytics.',
    icon: 'Server'
  }
];

export const CATEGORIES = [
  { id: 'all', label: 'All Tools', color: '#64748b', icon: 'LayoutGrid' },
  { id: 'development', label: 'Development', color: '#3b82f6', icon: 'Code2' },
  { id: 'design', label: 'Design', color: '#ec4899', icon: 'PenTool' },
  { id: 'productivity', label: 'Productivity', color: '#f59e0b', icon: 'CheckSquare' },
  { id: 'deployment', label: 'Deployment', color: '#10b981', icon: 'Rocket' },
  { id: 'devops', label: 'DevOps', color: '#6366f1', icon: 'Server' },
  { id: 'ai', label: 'AI & ML', color: '#8b5cf6', icon: 'Bot' },
  { id: 'iot', label: 'IoT', color: '#14b8a6', icon: 'Container' }
];

export const WORKFLOWS = [
  {
    id: 'dev-start',
    title: 'Start Dev Environment',
    description: 'Open VS Code, GitHub, and Localhost',
    actions: ['open:vscode', 'open:github', 'cmd:npm run dev']
  },
  {
    id: 'deploy-prod',
    title: 'Deploy to Production',
    description: 'Run tests, build, and deploy to Vercel',
    actions: ['cmd:npm test', 'cmd:npm run build', 'open:vercel']
  },
  {
    id: 'morning-routine',
    title: 'Morning Routine',
    description: 'Check Linear, Notion, and Email',
    actions: ['open:linear', 'open:notion', 'open:gmail']
  }
];
